AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - 'test/**/*'

Style/StringConcatenation:
  Exclude:
    - 'test/**/*'

Gemspec/DevelopmentDependencies:
  Enabled: false
